server:
  port: 8761
  
eureka:
  instance:
     # 注册时使用ip而不是主机名
    prefer-ip-address: true
    # 指定此实例的ip
    ip-address: 192.168.1.2
    # instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true # 表示是否从Eureka Server获取注册信息,默认为true.因为这是一个单点的Eureka Server,不需要同步其他的Eureka Server节点的数据,这里设置为false 
    register-with-eureka: true # 表示是否将自己注册到Eureka Server,默认为true.由于当前应用就是Eureka Server,故而设置为false.
    service-url: 
      # 设置与Eureka Server的地址,查询服务和注册服务都需要依赖这个地址.默认是http://localhost:8761/eureka/;多个地址可使用','风格.
      defaultZone: http://admin:admin@192.168.1.1:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.49
    enable-self-preservation: false       # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    
security:
  basic:
    enabled: false # true开启基于Http basic认证,false不开启
  user:
    name: admin
    password: admin
    
# actuator 权限    
management:
  security:
    enabled: false
    
# 日志
logging:
  config: classpath:log4j2.xml